### ISSUE TITLE
Crate link for nyx is incorrect

### ISSUE THREAD

**Issue by ChristopherRabotin** [AeroRust/awesome-space#2]
The link should be https://crates.io/crates/nyx-space/ . The code is also available on Gitlab here: https://gitlab.com/chrisrabotin/nyx .

**Comment by elpiel** [comment]
Hey @ChristopherRabotin sorry for the late delay!
I did fix the crates.io link (apparently) but forgot to add the gitlab link!
I did now and thanks for the input!

Hope we can talk to each other in Discord if you still have interest on working over some related projects :yum: 

Feel free to re-open or open a PR if you find anything else,
